apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deploy
  namespace: stage
  labels:
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
        env: canary
    spec:
      containers:
      - name: whoami
        image: acrdemo4.azurecr.io/whoami:latest
        ports:
        - containerPort: 4000
      imagePullSecrets:
      - name: secret-stage
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 4000
  selector:
    app: whoami