apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deploy
  namespace: prod
  labels:
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
        env: prod
    spec:
      containers:
      - name: whoami
        image: acrdemo4.azurecr.io/whoami:latest
      imagePullSecrets:
      - name: secret-prod
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 4000
  selector:
    app: whoami
